stack:
  services:
    web:
      image:
        tag: sha-TO-BE-REPLACED-BY-BUILDER-WORKFLOW
      replicaCount: 2
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      # Uncomment to pin a custom hostname:
      # ingress:
      #   host: rapidqcms.prod-sci-data.prod.czi.team
    postgres:
      persistence:
        pvc:
          resources:
            requests:
              storage: 50Gi
