stack:
  services:
    web:
      image:
        tag: sha-7c079e7
      replicaCount: 1
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
    postgres:
      persistence:
        pvc:
          resources:
            requests:
              storage: 10Gi
